[project]
name = "karki-aayog-pratibedan-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "aioredis>=2.0.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.135.2",
    "langchain>=1.2.13",
    "langchain-google-genai>=4.2.1",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.1.12",
    "langchain-pymupdf4llm>=0.5.0",
    "langchain-text-splitters>=1.1.1",
    "pgvector>=0.4.2",
    "psycopg2>=2.9.11",
    "pypdf>=6.9.2",
    "python-dotenv>=1.2.2",
    "rank-bm25>=0.2.2",
    "redis>=7.4.0",
    "ruff>=0.15.9",
    "sentence-transformers>=5.3.0",
    "slowapi>=0.1.9",
    "sqlalchemy>=2.0.48",
    "ty>=0.0.29",
]
