"""modified embeding dimension

Revision ID: 4bfa3f1b1e72
Revises:
Create Date: 2026-04-26 19:49:05.659281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy as pgvector

# revision identifiers, used by Alembic.
revision: str = "4bfa3f1b1e72"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "embedding",
        existing_type=pgvector.vector.VECTOR(dim=384),
        type_=pgvector.vector.VECTOR(dim=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "embeddings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "embeddings",
        "embedding",
        existing_type=pgvector.vector.VECTOR(dim=1024),
        type_=pgvector.vector.VECTOR(dim=384),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
